---

- name: Generate task file from template
  hosts: mediacenter
  gather_facts: no
  connection: local
  tags: build
  pre_tasks:
    - include_vars: "vars/main.yml"
  tasks:
  - name: "Building configuration for farbic leafs"
    template: >
      src={{ playbook_dir }}/templates/main.j2
      dest={{ playbook_dir }}/tasks/main.yml
    tags: build

