---

- name: Run mediacenter playbook
  hosts: mediacenter
  gather_facts: no
  connection: local
  tags: build
  pre_tasks:
    - include_vars: "vars/main.yml"
  tasks: 
    - name: Add Group
      group:
        name: htpc
        state: present
    - name: Add User
      user:
        name: htpc
        comment: htpc
        group: htpc
        state: present
    - name: Run main task file
      import_tasks: tasks/main.yml

- hosts: mediacenter
  gather_facts: yes
  connection: local
  tags: build
  pre_tasks:
    - include_vars: "vars/main.yml"
  roles:
  - { role: reverse_proxy, service_name: deluge, dest_port: "8112", listen_port: 80}
  - { role: reverse_proxy, service_name: htpcmanager, dest_port: "8085", listen_port: 80}
  - { role: reverse_proxy, service_name: couchpotato, dest_port: "5050", listen_port: 80}
  - { role: reverse_proxy, service_name: plexpy, dest_port: "8181", listen_port: 80}
  - { role: reverse_proxy, service_name: plex, dest_port: "32400", listen_port: 80}
  - { role: reverse_proxy, service_name: unifi, dest_port: "8843", listen_port: 80}
  - { role: reverse_proxy, service_name: tvheadend, dest_port: "9982", listen_port: 80}
  - { role: reverse_proxy, service_name: duplicati, dest_port: "9191", listen_port: 80}
  - { role: reverse_proxy, service_name: sikrage, dest_port: "8081", listen_port: 80}
  
