---
# tasks file for docker-plex

- name: Create Plex server config directory
  file: path=/opt/docker-plex/config/ state=directory owner=htpc group=htpc

- name: Download and Start PlexMediaServer Container
  docker_container:
    name: plex
    image: linuxserver/plex
    state: started
    restart_policy: always
    pull: yes
    volumes:
      - "/opt/docker-plex/config/:/config/"
      - "/data/:/data/"
    network_mode: host
    env:
      PUID: htpc
      PGID: htpc
      VERSION: latest
      TZ: UTC
